### ISSUE TITLE
CircuitBreaker metric question

### ISSUE THREAD

**Issue by Macarse** [RobWin/resilience4j-spring-boot2-demo#2]
Hello

I am trying to get the same information shown in the `/health` endpoint without enabling the health indicator. I guess this can be done through metrics. 

In the doc at http://resilience4j.github.io/resilience4j/#_circuitbreaker_5 it says:
```
Metrics are automatically published on the Metrics endpoint.
For example:

{
    "names": [
        "resilience4j.circuitbreaker.backendA.successful",
        "resilience4j.circuitbreaker.backendA.failed",
        "resilience4j.circuitbreaker.backendA.buffered",
        "resilience4j.circuitbreaker.backendA.buffered_max",
        "resilience4j.circuitbreaker.backendA.not_permitted",
        "resilience4j.circuitbreaker.backendB.successful",
        "resilience4j.circuitbreaker.backendB.failed",
        "resilience4j.circuitbreaker.backendB.buffered",
        "resilience4j.circuitbreaker.backendB.buffered_max",
        "resilience4j.circuitbreaker.backendB.not_permitted"
        ]
}
```

If I run the code and hit http://localhost:9080/actuator/metrics those names are not present. what I am missing?

**Comment by RobWin** [comment]
Yes, you are right. The documentation must be updated. 
In the latest version v0.14.1 resilience4j-micrometer and resilience4j-prometheus use tags to specify the circuitbreaker name now. The name is not part of the metric name anymore.
But you can use the config property `resilience4j.circuitbreaker.metrics.use_legacy_binder = true` to use the old style.

**Comment by Macarse** [comment]
@RobWin thanks for your reply. I am trying to get the failure rate. 

I see that the `CircuitBreakerHealthIndicator ` (https://github.com/resilience4j/resilience4j/blob/master/resilience4j-spring-boot2/src/main/java/io/github/resilience4j/circuitbreaker/monitoring/health/CircuitBreakerHealthIndicator.java#L68) uses `metrics.getFailureRate()` but I don't see that exposed in the metrics.

Is there a better way to get it or I should use something like `successful` and `failed` to calculate the failure rate?

**Comment by RobWin** [comment]
True, we don't have a failure rate metric at the moment. That's missing. We should create an issue.

You can only use successful/failed when `resilience4j_circuitbreaker_buffered_calls` is equal to `resilience4j_circuitbreaker_max_buffered_calls`. But you should not calculate it by your own.

**Comment by Macarse** [comment]
@RobWin happy to create a ticket and try to fix it myself.
Wouldn't be enough to link the metrics reported with `metrics.getFailureRate()`?

**Comment by RobWin** [comment]
Yes, that would be awesome:

Here:
https://github.com/resilience4j/resilience4j/blob/master/resilience4j-micrometer/src/main/java/io/github/resilience4j/micrometer/tagged/TaggedCircuitBreakerMetrics.java

Here: https://github.com/resilience4j/resilience4j/blob/master/resilience4j-prometheus/src/main/java/io/github/resilience4j/prometheus/collectors/CircuitBreakerMetricsCollector.java

and here: https://github.com/resilience4j/resilience4j/blob/master/resilience4j-metrics/src/main/java/io/github/resilience4j/metrics/CircuitBreakerMetrics.java

**Comment by Macarse** [comment]
Thanks for the answers!
